name: Bump Version on Merge

on:
  push:
    branches:
      - releases

jobs:
  bump-version:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10.17.1
      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 20
      - name: Get branch name
        id: branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      - name: Bump version
        run: |
          BRANCH_NAME="${{ steps.branch.outputs.branch_name }}"
          if [[ "$BRANCH_NAME" == *"major"* ]]; then
            pnpm version major --no-git-tag-version
          elif [[ "$BRANCH_NAME" == *"minor"* ]]; then
            pnpm version minor --no-git-tag-version
          else
            pnpm version patch --no-git-tag-version
          fi
      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore(release): bump version [skip ci]"
          git push
