name: CI
description: >
  Runs tests, uploads coverage, and publishes a test report for all pull requests to main or when manually triggered. Ensures code quality and provides feedback on test results and coverage in the GitHub Actions UI.
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (tag, branch, or commit hash) to check out for testing.'
        required: false
        default: ''
    required: false
    default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10.17.1
      - name: Use Node.js 20.x
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm run test -- --reporter=junit --outputFile=./junit.xml

      - name: Publish Test Report
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3
        if: always()
        with:
          name: Test Results
          path: junit.xml
          reporter: jest-junit
